version: "3"
services:
  kairos-redis-1:
    hostname: kairos-redis
    container_name: kairos-redis
    image: redis:5.0-rc3
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always
  kairos-redis-2:
    hostname: kairos-redis
    container_name: kairos-redis
    image: redis:5.0-rc3
    ports:
      - "6380:6379"
    expose:
      - 6379
    restart: always
    
    